name: Build MongoDB Realm

on: [push, pull_request, create]

jobs: 
  build: 
    runs-on: macos-latest
    steps: 
    - uses: actions/checkout@v2

    # SET THE ENVIRONMENT VARIABLES FOR USE LATER ON
    - name: "Store current time in variable"
      run: echo "CURRENT_TIME=$(date + '%Y-%m-%d-%s')" >> $GITHUB_ENV

    - name: "Is this a push to the Main branch?"
      if: ${{ github.ref == 'refs/heads/main' }}
      run: echo "REALM_APP_ID=flexsync" >> $GITHUB_ENV

    - name: "Is this a push to the Production branch"
      if: ${{ github.ref == 'refs/heads/prod' }}
      run: echo "REALM_APP_ID=flexsync-prod" >> $GITHUB_ENV

    - name: "Is this a new feature branch?"
      if: ${{ !env.REALM_APP_ID && github.event_name == 'create' }}
      run: |
        # Create a new environment variable to store the name of the feature branch
        ref=$(echo ${{ github.ref }})
        branch=$(echo "${ref##*/}")
        echo "FEATURE_BRANCH=$branch" >> $GITHUB_ENV

        # Assuming the JSON file is simple and the update is straightforward
        # For more complex updates, consider a separate script file
        json_file="development.config.json"

        # Read JSON file and modify it using jq (for example, add a new field)
        jq '. + {"newBranch": "${{ github.ref_name }}"}' "$json_file" > temp.json && mv temp.json "$json_file"

        # Check if there are any changes. If so, commit and push them.
        if [ -n "$(git status --porcelain)" ]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "$json_file"
          git commit -m "Update JSON file for new branch"
          git push
        else
          echo "No changes to commit"
        fi

    - name: "Set environment variables for all other runs"
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        # Create a new environment variable named IS_DYNAMICALLY_GENERATED_APP to indicate this is
        # a dynamically generated app that should be deleted later in this workflow
        echo "IS_DYNAMICALLY_GENERATED_APP=true" >> $GITHUB_ENV

    - name: "Test environment variable outputs"
      run: |
        echo "REALM_APP_ID: ${{ env.REALM_APP_ID }}"
