name: Build MongoDB Realm

on: [push, pull_request, create]

jobs: 
  build: 
    runs-on: macos-latest
    steps: 
    - uses: actions/checkout@v2

    # SET THE ENVIRONMENT VARIABLES FOR USE LATER ON
    - name: "Store current time in variable"
      run: echo "CURRENT_TIME=$(date + '%Y-%m-%d_%s')" >> $GITHUB_ENV

    - name: "Is this a push to the Main branch?"
      if: ${{ github.ref == 'refs/heads/main' }}
      run: echo "REALM_APP_ID=flexsync" >> $GITHUB_ENV

    - name: "Is this a push to the Production branch"
      if: ${{ github.ref == 'refs/heads/prod' }}
      run: echo "REALM_APP_ID=flexsync-prod" >> $GITHUB_ENV

    - name: "Is this a new feature branch?"
      if: ${{ !env.REALM_APP_ID && github.event_name == 'create' }}
      run: |
        # Create a new environment variable to store the name of the feature branch
        ref=$(echo ${{ github.ref }})
        branch=$(echo "${ref##*/}")
        echo "FEATURE_BRANCH=$branch" >> $GITHUB_ENV

        # Check if a Realm app already exists for this feature branch
        # Note: This requires the IP addres of the Github Actions vm to be in the Altas access list
        output=*null
        
        if [[ $output == *null ]]; then
          echo "No Realm app found for this branch.  A new app will be pushed later in this workflow"
        else
          echo "A Realm app was found for this branch. Updates will be pushed to the existing app later"
          app_id=$(echo $output | sed 's/^.*realm_app_id" : "\([^"]*\).*/\1/')
          echo "REALM_APP_ID=$app_id" >> $GITHUB_ENV
        fi

        # Update the realmAppId in the development.config.json environment file
        # Set the appId to contain the branch name to ensure its unique
        printf '{\n "realmAppId": "flexsync-%s"\n}' "$branch" > development.config.json

    - name: "Set environment variables for all other runs"
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        # Create a new environment variable named IS_DYNAMICALLY_GENERATED_APP to indicate this is
        # a dynamically generated app that should be deleted later in this workflow
        echo "IS_DYNAMICALLY_GENERATED_APP=true" >> $GITHUB_ENV

    - name: "Test environment variable outputs"
      run: |
        echo "REALM_APP_ID: ${{ env.REALM_APP_ID }}"
